"""Unit tests for the feature pipeline.

Cross-checks RSI(14), MACD(12,26,9), ATR(14) against the same close-only
math the TypeScript pattern-analyzer uses, on a fixed deterministic series.
The expected numbers below were generated by transliterating the TS code
in this repo and feeding it the same inputs; they are reference values for
the Python port and lock the contract for Phase 2.
"""
from __future__ import annotations

import math
from datetime import datetime, timedelta, timezone

from app.features import (
    MIN_CANDLES_FOR_FEATURES,
    atr,
    bollinger,
    build_feature_vector,
    build_feature_vectors_for_series,
    ema_series,
    macd,
    resample_to_candles,
    rsi,
)


def _series(n: int = 60) -> list[float]:
    """Deterministic series with both trend and oscillation."""
    return [100.0 + i * 0.5 + math.sin(i / 3.0) * 2.0 for i in range(n)]


def test_rsi_constant_series_is_neutral_or_max():
    # Strictly increasing series -> avg loss is 0 -> RSI = 100 by definition.
    assert rsi([float(i) for i in range(1, 30)], 14) == 100.0
    # Too-short series falls back to neutral 50.
    assert rsi([1.0, 2.0, 3.0], 14) == 50.0


def test_rsi_bounded_zero_to_hundred():
    s = _series(50)
    val = rsi(s, 14)
    assert 0.0 <= val <= 100.0


# ---- TS<->Python parity locks --------------------------------------------------
# Reference values produced by `node artifacts/ml-engine/tests/_gen_reference.mjs`
# which transliterates the TypeScript pattern-analyzer (RSI/MACD/ATR) line-for-
# line. If TS drifts, regenerate and update these numbers; if Python drifts the
# tests below will fail. This is the deterministic parity check the Phase-1 task
# spec requires.
TS_REFERENCE_60 = {
    "rsi14": 97.10584318174404,
    "macdLine": 3.475148004515418,
    "macdSignal": 3.2213864721509173,
    "macdHist": 0.25376153236450083,
    "atr14": 0.9080011731221028,
}


def test_rsi_matches_typescript_reference():
    assert math.isclose(rsi(_series(60), 14), TS_REFERENCE_60["rsi14"], rel_tol=1e-12, abs_tol=1e-12)


def test_macd_matches_typescript_reference():
    m = macd(_series(60))
    assert math.isclose(m["line"], TS_REFERENCE_60["macdLine"], rel_tol=1e-12, abs_tol=1e-12)
    assert math.isclose(m["signal"], TS_REFERENCE_60["macdSignal"], rel_tol=1e-12, abs_tol=1e-12)
    assert math.isclose(m["hist"], TS_REFERENCE_60["macdHist"], rel_tol=1e-12, abs_tol=1e-12)


def test_atr_matches_typescript_reference():
    assert math.isclose(atr(_series(60), 14), TS_REFERENCE_60["atr14"], rel_tol=1e-12, abs_tol=1e-12)
# --------------------------------------------------------------------------------


def test_ema_short_circuits_for_short_inputs():
    assert ema_series([], 9) == []
    out = ema_series([10.0, 12.0, 11.0], 9)
    # First value is the seed; remaining values lie between min and max input.
    assert out[0] == 10.0
    for v in out[1:]:
        assert 10.0 <= v <= 12.0


def test_macd_default_when_too_short():
    m = macd([1.0] * 10)
    assert m == {"line": 0.0, "signal": 0.0, "hist": 0.0}


def test_macd_hist_equals_line_minus_signal():
    s = _series(60)
    m = macd(s)
    assert math.isclose(m["hist"], m["line"] - m["signal"], abs_tol=1e-12)


def test_atr_zero_for_short_series_then_positive():
    assert atr([1.0, 2.0], 14) == 0.0
    s = _series(40)
    a = atr(s, 14)
    assert a > 0


def test_bollinger_pctb_is_in_unit_interval_when_enough_data():
    s = _series(40)
    bb = bollinger(s, 20, 2.0)
    assert bb["upper"] >= bb["middle"] >= bb["lower"]
    assert bb["width"] >= 0
    # PctB can technically exceed [0,1] in extreme cases, but for this gentle
    # series it should sit comfortably inside.
    assert -1.0 <= bb["pctB"] <= 2.0


def test_bollinger_short_circuits_for_short_inputs():
    bb = bollinger([1.0, 2.0, 3.0], 20, 2.0)
    assert bb["upper"] == bb["middle"] == bb["lower"] == 3.0
    assert bb["pctB"] == 0.5


def test_resample_to_candles_skips_empty_buckets_and_uses_last_in_bucket():
    base = datetime(2025, 1, 1, tzinfo=timezone.utc)
    bucket_ms = 60_000  # 1 minute
    ticks = [
        (base + timedelta(seconds=10), 100.0),
        (base + timedelta(seconds=20), 101.0),
        (base + timedelta(seconds=50), 102.0),  # last in bucket0 -> 102
        # bucket 1 is empty (no ticks between :60 and :120) -> skipped
        (base + timedelta(seconds=130), 103.0),
        (base + timedelta(seconds=170), 104.0),  # last in bucket2 -> 104
    ]
    closes = resample_to_candles(ticks, bucket_ms)
    assert closes == [102.0, 104.0]


def test_resample_ignores_invalid_prices():
    base = datetime(2025, 1, 1, tzinfo=timezone.utc)
    ticks = [
        (base, 0.0),
        (base + timedelta(seconds=1), -5.0),
        (base + timedelta(seconds=2), float("nan")),
    ]
    assert resample_to_candles(ticks, 60_000) == []


def test_build_feature_vector_returns_none_below_minimum():
    s = _series(MIN_CANDLES_FOR_FEATURES - 1)
    assert build_feature_vector(s) is None


def test_build_feature_vectors_for_series_matches_per_call():
    """Task #481 — the batch feature builder used by the trainer must
    produce bit-identical output to the per-call ``build_feature_vector``
    for every valid bar. The trainer's 5m dataset build relied on this
    equivalence to drop from O(N²) (which hung the campaign on bonk's
    growing 5m candle history) to O(N).
    """
    import random
    rng = random.Random(20260424)
    closes = [100.0]
    for _ in range(400):
        closes.append(max(0.01, closes[-1] * (1 + rng.gauss(0, 0.012))))
    batch = build_feature_vectors_for_series(closes)
    # Below MIN_CANDLES_FOR_FEATURES the per-call path returns None and
    # so must the batch slot.
    for k in range(MIN_CANDLES_FOR_FEATURES - 1):
        assert batch[k] is None
    sampled = 0
    for k in range(MIN_CANDLES_FOR_FEATURES - 1, len(closes)):
        expected = build_feature_vector(closes[: k + 1])
        actual = batch[k]
        assert expected is not None and actual is not None
        assert expected.keys() == actual.keys()
        for key in expected:
            assert math.isclose(
                expected[key], actual[key], rel_tol=1e-12, abs_tol=1e-12,
            ), f"mismatch at k={k} key={key}: {expected[key]} vs {actual[key]}"
        sampled += 1
    assert sampled > 350  # enough coverage on the rolling window


def test_build_feature_vectors_for_series_short_circuits_below_minimum():
    s = _series(MIN_CANDLES_FOR_FEATURES - 1)
    out = build_feature_vectors_for_series(s)
    assert len(out) == len(s)
    assert all(v is None for v in out)


def test_build_feature_vector_full_shape_when_enough_data():
    s = _series(60)
    vec = build_feature_vector(s)
    assert vec is not None
    # Task #365 — Quant-Only Enforcement permanently shut the LLM-derived
    # `news_*` one-hot block at the FEATURE level; `build_feature_vector`
    # no longer appends it (see app/features.py around lines 445-454).
    # The expected key set therefore must NOT include `news_*` — that
    # channel is now exercised independently by
    # `tests/test_news_tag_vocab_parity.py::test_news_tag_features_emits_canonical_columns`
    # against the `news_tag_features()` helper directly.
    expected_keys = {
        "candleCount", "lastPrice",
        "ret1", "ret5", "ret10", "momentum", "realizedVol",
        "rsi14", "macdLine", "macdSignal", "macdHist",
        "atr14", "atrPct",
        "ema9", "ema21", "emaSpreadPct",
        "distFromEma9Pct", "distFromEma21Pct",
        "bbUpper", "bbMiddle", "bbLower", "bbWidth", "bbPctB", "bbWidthPct",
        # Task #517 — rolling 60-bar |ret1| z-score.
        "volZScore60",
    }
    assert set(vec.keys()) == expected_keys
    assert vec["candleCount"] == 60
    assert vec["lastPrice"] == s[-1]
    # Sanity: macdHist == macdLine - macdSignal
    assert math.isclose(vec["macdHist"], vec["macdLine"] - vec["macdSignal"], abs_tol=1e-12)


# Task #517 — `volZScore60` margin-improvement coverage. Locks the
# numeric contract on a deterministic series, the zero-fallback when the
# rolling window has no dispersion (so the booster never sees a NaN /
# inf), and the parity between the per-call and batch builders. The
# matching slice-level proof — that adding `volZScore60` to
# FEATURE_COLUMNS lifts dogwifcoin@1d's `raw_STABLE_share` well above
# the 5% verification floor — lives in
# `tests/test_training.py::test_task507_focused_diagnostic_recovers_all_stuck_slices`.
def test_vol_zscore_60_matches_manual_rolling_zscore():
    """The feature is `(|ret1[k]| - mean_60) / std_60`, where the
    window is the trailing 60 absolute 1-bar returns ending at bar k
    (inclusive). Validate against an independent re-derivation on a
    deterministic series so a refactor that quietly changes the
    window length / inclusion / std flavour fails fast.
    """
    import random
    rng = random.Random(20260428)
    closes = [100.0]
    for _ in range(120):
        closes.append(max(0.01, closes[-1] * (1 + rng.gauss(0, 0.01))))
    vec = build_feature_vector(closes)
    assert vec is not None
    # Independent recomputation: walk through abs(ret1) over the last
    # 60 bars and z-score the most recent value with sample std (ddof=1)
    # to mirror `pd.Series.rolling(60, min_periods=10).std()`.
    rets = [
        (closes[i] - closes[i - 1]) / closes[i - 1]
        for i in range(1, len(closes))
    ]
    abs_rets = [abs(r) for r in rets]
    window = abs_rets[-60:]
    mu = sum(window) / len(window)
    var = sum((x - mu) ** 2 for x in window) / (len(window) - 1)
    sd = math.sqrt(var)
    expected = (abs_rets[-1] - mu) / sd
    assert math.isclose(vec["volZScore60"], expected, rel_tol=1e-12, abs_tol=1e-12)


def test_vol_zscore_60_is_zero_when_window_has_no_dispersion():
    """A flat-price segment (every return is 0) produces a 0-std
    window, which would yield NaN under naive division. The feature
    must short-circuit to 0.0 so downstream LightGBM training never
    sees a NaN / inf in the column.
    """
    closes = [100.0] * 80   # >= MIN_CANDLES_FOR_FEATURES, all returns are exactly 0
    vec = build_feature_vector(closes)
    assert vec is not None
    assert vec["volZScore60"] == 0.0
    assert math.isfinite(vec["volZScore60"])


def test_vol_zscore_60_is_zero_when_history_below_min_periods():
    """`min_periods=10` on the rolling window — fewer than 10 prior
    absolute returns means the z-score is undefined. The per-call
    builder still requires `MIN_CANDLES_FOR_FEATURES` bars overall, so
    we check the early-history fallback by building from a length
    that's just past the MACD minimum but within the 10-return
    short-circuit reach (none of the realistic series this trains on
    will hit it, but the contract must hold by construction).
    """
    n = MIN_CANDLES_FOR_FEATURES   # exactly 35 closes => 34 returns; >= 10 ⇒ window is computed
    closes = [100.0 + i for i in range(n)]
    vec = build_feature_vector(closes)
    assert vec is not None
    assert math.isfinite(vec["volZScore60"])


def test_vol_zscore_60_batch_matches_per_call():
    """The batch builder must produce bit-identical `volZScore60` at
    every bar k as a fresh per-call `build_feature_vector(closes[:k+1])`
    would — the trainer's pooled-dataset build path uses the batch
    builder, so any drift between the two would silently train and
    score on different feature contracts.
    """
    import random
    rng = random.Random(20260428_2)
    closes = [100.0]
    for _ in range(180):
        closes.append(max(0.01, closes[-1] * (1 + rng.gauss(0, 0.011))))
    batch = build_feature_vectors_for_series(closes)
    sampled = 0
    for k in range(MIN_CANDLES_FOR_FEATURES - 1, len(closes)):
        per_call = build_feature_vector(closes[: k + 1])
        assert per_call is not None and batch[k] is not None
        assert math.isclose(
            per_call["volZScore60"], batch[k]["volZScore60"],
            rel_tol=1e-12, abs_tol=1e-12,
        ), f"volZScore60 mismatch at k={k}: {per_call['volZScore60']} vs {batch[k]['volZScore60']}"
        sampled += 1
    assert sampled > 100
